### ISSUE TITLE
Enhance Tables

### ISSUE THREAD

**Issue by lgueldenhaupt** [lgueldenhaupt/BA#1]
As a user i want to sort any table i see by every possible column. 
Also i want to be able to search in a table.

**Comment by goforthanddie** [comment]
Geil, das ging ja flott! Könntest du die Columns wo man sie zusammenklickt alphanumerisch sortieren? Fällt mir grade auf, dass man sich dann vllt. nich so den kompletten Wolf sucht :D, gleiches für die Filterbuttons wenns geht :)! Good job.

**Comment by goforthanddie** [comment]
Wenn ich die View von List auf Card switche verliert er die Columns, du kannst den Switch eigentlich rausnehmen, glaube nicht dass sich das jemand als Cards angucken möchte :d

**Comment by lgueldenhaupt** [comment]
ist raus mit dem nächsten commit
