### ISSUE TITLE
LDAP + SSL?

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#15]
Notfalls SSL only für die Seite?

**Comment by goforthanddie** [comment]
So, der LDAP-Server hier unterstützt scheinbar kein ldaps, reicht dann also wenn die Seite mit SSL läuft.

**Comment by lgueldenhaupt** [comment]
Wenn man ssl benutzen möchte muss man ein Zertifikat kaufen oder?

**Comment by goforthanddie** [comment]
Da kann man erstmal ein selbstsigniertes benutzen, ich bau mal eins, aber ich frage auch mal Peter ob wir nicht eins haben...

**Comment by goforthanddie** [comment]
[cert.zip](https://github.com/lgueldenhaupt/BA/files/1520765/cert.zip)

**Comment by goforthanddie** [comment]
hab ssl jetzt auf server basis eingebaut
