### ISSUE TITLE
Spaltenkonfiguration speichern

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#16]

**Comment by lgueldenhaupt** [comment]
fertig

**Comment by goforthanddie** [comment]
hmmm, also er speichert es bei einem projekt, wenn ich dann bei einem zweiten projekt die spaltenkonfiguration ändere verschwindet sie wieder beim ersten :o

**Comment by lgueldenhaupt** [comment]
ja, wäre vielleicht smart, wenn ich die nicht immer überschreiben sondern hinzufügen würde :D

**Comment by goforthanddie** [comment]
:+1:

**Comment by lgueldenhaupt** [comment]
sollte jetzt besser sein. 👍

**Comment by goforthanddie** [comment]
Top! :D Kannste noch die Sortierung speichern und ääh, ist es möglich unter Actions was hinzuzufügen damit man (mehrere) Zeilen highlighten kann?
