### ISSUE TITLE
Plot-Thumbnail in extra Spalte

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#17]

**Comment by goforthanddie** [comment]
bein einlesen von vielen configs rutscht scheinbar mal was durch, hier im beispiel wars config 2 und 127.

**Comment by lgueldenhaupt** [comment]
Sollte jetzt besser sein :D das dom-to-image package kommt scheinbar nicht so schnell hinterher. Kannst du nochmal prüfen?

**Comment by goforthanddie** [comment]
jo, scheint gut zu funktionieren, aber jetzt speichert er die spalten konfiguration/anzahl der datensätze nichtmehr D:

**Comment by lgueldenhaupt** [comment]
Hab jetzt einen Button zum manuellen Schließen nach dem Upload eingebaut. Damit tritt das Problem bei mir nicht mehr auf (mehrmals mit ca. 200 Dateien getestet).

**Comment by goforthanddie** [comment]
sah erstmal gut aus, jetzt fügt zeigt er mir keine configs mehr an in der liste, in die DB werden sie aber hinzugefügt D:. auch wenn ich ein neues projekt mache, läd er die configs hoch, aber anschließend bleibt die liste leer :o

**Comment by lgueldenhaupt** [comment]
Ich vermute das hat nichts mit dem modal zu tun. Schaue mir das nachher Mal an.

**Comment by lgueldenhaupt** [comment]
sollte wieder klappen.

**Comment by goforthanddie** [comment]
:+1:
