### ISSUE TITLE
Projektübersicht / Filter

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#2]
Liste der verfügbaren Filter etwas kondensieren, eher so wie 'ne Wolke anstatt einer Liste. 
Speichern der zuletzt benutzten Filter (Projektgebunden).
Spalten dynamisch in der Übersicht auswählen können, Name, Description sind eigentlich erstmal uninteressant.
Allgemein weniger Spacing in den Listen.

**Comment by lgueldenhaupt** [comment]
Liste der Filter wurde verkleinert.

**Comment by goforthanddie** [comment]
Die Filter klappen nichtmehr aus wenn ich welche hinzugefügt habe, kann also die Werte der Filter nichtmehr wählen.

**Comment by lgueldenhaupt** [comment]
Auf der aktuellen Version läuft es bei mir. Update nochmal und führ vorher "npm install" aus. Da ich neue packages hinzugefügt habe, kann es zu Problemen kommen, wenn die nicht aktuell sind.

**Comment by lgueldenhaupt** [comment]
Ah okay, ich hab das Problem jetzt auch. Tritt nur beim Navigieren zu der Seite auf. Beim neu laden läuft es. Arbeite am fix.

**Comment by lgueldenhaupt** [comment]
Habs gefixt. Eigenartiger Bug.

**Comment by goforthanddie** [comment]
Top, nu hab ich gleich noch was gefunden, da müssen wir uns aber vllt. mal unterhalten was mehr Sinn macht, da die Flags einfach Integer sind, wirs natürlich hässlich, wenn man bei max_epochs z.B. 5 angibt, da will man natürlich nicht dass die "Flag" übersetzt wird weil es ja an dieser Stelle keine Flag sondern halt die Zahl 5 ist. Eine Möglichkeit wäre, dass man quasi für jeden Parameter 'nen Typ (Flag, Int) angeben kann und dementsprechend übersetzt wird oder nicht, oder die Flags werden alle in Hexadezimal umgestellt. Kein Plan was schlauer ist. Jedenfalls wäre es nice, wenn man auf Filter klickt, dass die Felder farblich getoggelt werden können, dann sieht man sofort welche man schon angeklickt hat und kann diese auch noch rausnehmen wenn man sich verklickt hat ;). Wann sollen wir uns mal wieder treffen?

**Comment by lgueldenhaupt** [comment]
Alle Punkte soweit umgesetzt.

**Comment by goforthanddie** [comment]
Hm, ich kann die Filter jetzt toggeln, aber sie erscheinen nicht links in der Liste :o

**Comment by lgueldenhaupt** [comment]
jo. das war mein Versuch die Filter zu sortieren. Hat nicht geklappt. Sie wurden angezeigt wenn man zu einer anderen Seite navigiert und dann wieder zurück. Habe ich jetzt erstmal raus genommen. Muss ich mir was anderes überlegen.
