### ISSUE TITLE
Slider für Pagination auf Detailseite von Config

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#20]

**Comment by lgueldenhaupt** [comment]
Fertig

**Comment by goforthanddie** [comment]
kannste das noch persistent machen? sowohl bei den projekten als auch bei den configs? ich denke das mit den configs kann ruhig projektübergreifend sein. wenn der slider bei den projekten für jedes projekt separat gespeichert werden kann wäre nice ;).
