### ISSUE TITLE
spalten sortierung

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#21]
moiiiiiiiin, hab grad festgestellt, dass er spalten nicht numerisch sortiert, also wenn ich z.B. als werte 5 10 15 50 habe, sortiert er mir das 10 15 5 50, kannste das numerisch sortieren lassen? :)

**Comment by lgueldenhaupt** [comment]
Jo, hab ich mal gemacht. Müsste so laufen
