### ISSUE TITLE
add button bei unrelated params

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#23]
wenn ich draufdrücke passiert nischt, verpeil ichs? aber dachte damit kann ich alias hinzufügen oder? :D

**Comment by lgueldenhaupt** [comment]
man kann die da drauf ziehen, um sie hinzuzufügen :D manuell welche hinzufügen lohnt sich nicht, oder? Ich kann daraus entweder eine art 'dropzone' machen, die ersichtlicher ist oder dem Button die Funktionalität geben manuell einen Alias zu erstellen.

**Comment by goforthanddie** [comment]
ja, stimmt. manuell lohnt eigentlich nich, hab ich halt vergessen :D
