### ISSUE TITLE
pfadanzeige von config

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#24]
mit in spalten aufnehmen

**Comment by lgueldenhaupt** [comment]
Ich denke diese Feature wird nichts. Die meisten Browser verbieten es den richtigen Pfad anzugeben. Chrome liefert zum bsp immer C:/fakepath/configresult. Ist ein Schutzmechanismus, damit der Server nicht das Dateisystem des Clients kennt..

**Comment by goforthanddie** [comment]
jo gut, mh, könntest du dann vllt doch noch einbauen, dass man zusätzlich files zu einer config uploaden kann? dann kann man wenigstens noch das trainierte netzwerk mit ablegen :o

**Comment by lgueldenhaupt** [comment]
sind das text files oder binaries, die du hochladen willst? Kommt dann drauf an, ob ich die auf dem Server ansich hochlade oder in die Datenbank schmeiße. Text files in die Datenbank wäre auf jeden Fall einfach, Dateien direkt auf dem Server speichern muss ich mal schauen.

**Comment by goforthanddie** [comment]
geht binaries ablegen inner DB?

**Comment by lgueldenhaupt** [comment]
geht, dann müsste ich GridFS verwenden, da MongoDB nur BSON dateien mit max 16MB speichert und alles was dem nicht entspricht muss aufgeteilt werden, was dann GridFS macht. Theoretisch

**Comment by goforthanddie** [comment]
hm, geht das easy in koexistenz oder musst du mongo gegen gridfs tauschen?

**Comment by lgueldenhaupt** [comment]
Austausch nicht. Das ist eine Erweiterung von MongoDB oder "Specification".

**Comment by lgueldenhaupt** [comment]
Okay, das ist auch keine große Sache merk ich gerade. Sollte also klappen. Wo soll dieser upload geschehen? Auf der Seite einer Config?
Und soll man die Datei dann downloaden können?

**Comment by goforthanddie** [comment]
drag&drop in den listen eintrag auf der projekt übersicht vllt?

**Comment by lgueldenhaupt** [comment]
Ok, irgendwie bin ich doch zu doof. :D es gibt diese Erweiterung, die aber für Meteor überaus sch... dokumentiert ist. Man kann nur anständig inserten aber nicht aus der DB ziehen oder Sachen löschen....
https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/gridfs/api.md
Das ist die geile UserAPI. Ich muss wohl irgendwie einen anderen Weg finden.

**Comment by lgueldenhaupt** [comment]
fertig
