### ISSUE TITLE
Mapping für Flags

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#3]
Fehlt noch...

**Comment by lgueldenhaupt** [comment]
Wie bekommt man die Flags? als separates File, also wieder upload? Oder manuelle Eingabe vom Nutzer?

**Comment by goforthanddie** [comment]
Jo, Upload wäre praktisch, aber evtl. zusätzlich manuelles Mapping erlauben, im Anhang eine Datei wie bei mir die Flags abgelegt sind, der Name wäre sozusagen der Part nach dem Punkt :o.
[flags.txt](https://github.com/lgueldenhaupt/BA/files/1477817/flags.txt)

**Comment by lgueldenhaupt** [comment]
Flag upload per drag&drop läuft. Entfernen der Flags auch. Manuelles hinzufügen kommt noch.

**Comment by lgueldenhaupt** [comment]
Fertisch
