### ISSUE TITLE
Plotfarben

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#5]
Feste Farben für Plots (oder auf Nutzer/Projektebene definierbar), Blau, Grün, Rot als Default.
Achsenbeschriftung (Epochen auf x-Achse, Loss/Accuracy auf y-Achse).

**Comment by lgueldenhaupt** [comment]
Fertisch. Die ersten 5 Trainingsets haben jetzt feste Farben. Danach wird eine generierte genommen.
Die Achsen sind beschriftet.
