### ISSUE TITLE
LDAP-Anbindung

### ISSUE THREAD

**Issue by goforthanddie** [lgueldenhaupt/BA#6]
Fehlt noch...

**Comment by lgueldenhaupt** [comment]
Fertig

**Comment by goforthanddie** [comment]
Boi, es workt. Aber es braucht eine kleine Änderung in der login.component.ts, 
`Meteor.loginWithLDAP(username, password, {dn: "CN=" + username + "," + dn, url: url}, (err) => {
                if (err) {
                    if (err.reason === "Invalid Credentials") {
                        this.notification.error("Invalid Credentials");
                    } else {
                        this.notification.error("Error: " + err.reason);
                    }
                } else {
                    this.notification.success("Logged in");
                }
            });`
In dem Call muss der Username an den LDAP mit übergeben werden, bisher war das Feld Username nämlich nutzlos, aber so funktioniert es, und ich fände es gut wenn er den Error falls es einen gibt einfach ausspuckt, dann weiß man evtl. schon etwas mehr. Inhalt der settings.json müsste so aussehen:
`
{
  "public": {
    "ldap": {
      "url": "ldap://ifn05.ifn.ing.tu-bs.de",
      "dn": "CN=Users,DC=ifn,DC=ing,DC=tu-bs,DC=de"
    }
  }
}
`
Dann klappts auch, allerdings muss er definitiv überprüfen ob das Passwort-Feld leer ist oder nicht, man kann nämlich auch ohne Passwort an den LDAP binden und dann würde er den auth durchführen. Nur wenn man ein Passwort in Kombi mit nem Namen angibt versucht er mit dem Passwort an den User zu binden, wenn das funzt, ist alles gut und er darf eingeloggt sein. Dann ist mir noch aufgefallen dass er mault wenn ich mich einmal mit Elshamy und dann nochmal mit elshamy anmelde, dann sagt er den Nutzer gibt es schon, evtl. einfach alles lowercasen vorm Login? Aber da kenn ich mich mit dem ldap package für Meteor nicht aus, da müsstest du mal gucken. AAAABER, geile Sache schonma :D.
